services:
    App\Shortener\Services\UrlValidator: ~
    App\Shortener\Services\DbStorage: ~
    App\Shortener\Services\UrlEncoder:
        arguments:
            $length: 8
            $validator: '@App\Shortener\Services\UrlValidator'
            $storage: '@App\Shortener\Services\DbStorage'
    App\Shortener\Services\UrlDecoder:
        arguments:
            $storage: '@App\Shortener\Services\DbStorage'